### ISSUE TITLE
Chrome更新后扩展丢失，需要重新安装

### ISSUE THREAD

**Issue by zyh12** [zeqianli/DoubanListingHelper#5]
疑似Chrome将本地安装的扩展视为不安全的，每次更新会清除。不过另一个通过本地安装的扩展却还在，原因未知( https://github.com/manojVivek/medium-unlimited )。

**Comment by zeqianli** [comment]
已更新polyfill（让firefox插件在chrome上也能工作的包），chrome上简单测试了下都可以用，很快发布。也已提交到chrome商店，还没批准，先用临时插件的方式用一下吧。新版本发布后如果还有问题可以开新的issue并附上链接～
